program: train.py
method: bayes
metric:
  name: f1_val
  goal: maximize
parameters:
  lr:
    distribution: uniform
    min: 8e-5
    max: 4e-4
  epochs:
    distribution: int_uniform
    min: 5
    max: 100
  batch_size:
    distribution: categorical
    values:
      #- "16"
      #- "32"
      #- "64"
      - "512"
      - "640"
